name: glovo_mate
description: "GlovoMate – Track delivery drivers in real-time."
publish_to: 'none'
version: 1.9.3+45

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_database: 11.3.10
  firebase_crashlytics: ^4.3.2

  # Location
  geolocator: ^13.0.2

  # Maps
  flutter_map: ^8.1.0
  latlong2: ^0.9.1

  # Notifications
  flutter_local_notifications: ^19.1.0

  # App update
  package_info_plus: ^8.0.0
  http: ^1.2.0
  open_filex: ^4.5.0
  permission_handler: ^11.3.0
  path_provider: ^2.1.0
  flutter_background_service: ^5.1.0
  android_intent_plus: ^6.0.0
  shared_preferences: ^2.5.5
  flutter_cache_manager: ^3.4.1
  crypto: ^3.0.3
  wakelock_plus: ^1.2.14
  firebase_app_check: ^0.3.2+10
  flutter_tts: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  adaptive_icon_background: "#FF9800"
  remove_alpha_ios: true
