import 'dart:async';
import 'dart:ui';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/material.dart';
import 'package:flutter_background_service/flutter_background_service.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:geolocator/geolocator.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:wakelock_plus/wakelock_plus.dart';
import 'firebase_options.dart';
import 'screens/splash_screen.dart';
import 'services/firebase_service.dart';

/// ID of the notification channel used by the foreground location service.
/// Must match the notificationChannelId passed to AndroidConfiguration below.
const String _locationChannelId = 'glovo_mate_location';

/// Unified location-update interval used by BOTH the foreground stream
/// (location_service.dart) and the background-service Timer. Keeping this in
/// one place guarantees identical cadence everywhere.
const Duration kLocationInterval = Duration(seconds: 3);

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Create the foreground-service notification channel BEFORE configuring
  // the service. On Android 8+, startForeground() crashes with
  // "Bad notification for startForeground" if the channel doesn't exist yet.
  await _createLocationNotificationChannel();

  await configureBackgroundService();

  runApp(const GlovoMateApp());
}

/// Create the notification channel required by the foreground service.
/// This MUST run before any startForeground() call.
Future<void> _createLocationNotificationChannel() async {
  final plugin = FlutterLocalNotificationsPlugin();
  const channel = AndroidNotificationChannel(
    _locationChannelId, // ← must match notificationChannelId below
    'تتبع الموقع',
    description: 'إشعار دائم أثناء تتبع الموقع في الخلفية',
    importance: Importance.low, // low = no sound, but persistent
    showBadge: false,
  );
  await plugin
      .resolvePlatformSpecificImplementation<
          AndroidFlutterLocalNotificationsPlugin>()
      ?.createNotificationChannel(channel);
}

/// Configure the background service before runApp.
Future<void> configureBackgroundService() async {
  final service = FlutterBackgroundService();

  await service.configure(
    androidConfiguration: AndroidConfiguration(
      onStart: onStart,
      autoStart: false,
      isForegroundMode: true,
      // Channel must already exist (created in main() above).
      notificationChannelId: _locationChannelId,
      initialNotificationTitle: 'GlovoMate',
      initialNotificationContent: 'تتبع الموقع قيد التشغيل',
      // A valid small icon resource is REQUIRED for startForeground on
      // Android 8+ — a missing/null icon throws "Bad notification".
      // @mipmap/ic_launcher is generated by Flutter and guaranteed to exist.
      foregroundServiceTypes: [AndroidForegroundType.location],
    ),
    iosConfiguration: IosConfiguration(
      autoStart: false,
      onForeground: onStart,
      onBackground: onIosBackground,
    ),
  );
}

/// Background service entry point.
///
/// PART 1: This isolate owns the ACTUAL GPS-read + Firebase-write loop,
/// completely independent of any UI/widget lifecycle. When the app is closed,
/// the UI State is destroyed but THIS Timer keeps running (the foreground
/// service keeps the process alive). So other members continue to see fresh
/// positions even after the user closes the app.
///
/// Reads `group_code` / `user_name` / `user_icon` from shared_preferences
/// (saved by the "remember session" feature) since this isolate has no access
/// to the UI's widget state.
@pragma('vm:entry-point')
void onStart(ServiceInstance service) async {
  DartPluginRegistrant.ensureInitialized();

  // Each isolate needs its own Firebase initialization.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  debugPrint('[BgService] onStart invoked.');

  // ── Acquire wake lock to prevent CPU sleep in Doze mode ──
  try {
    await WakelockPlus.enable();
    debugPrint('[BgService] Wake lock acquired.');
  } catch (e) {
    debugPrint('[BgService] Wake lock failed: $e');
  }

  StreamSubscription<DatabaseEvent>? _chatSubBg;
  int _foregroundNotifCounter = 0;
  service.on('stop').listen((event) async {
    debugPrint('[BgService] stop requested.');
    _chatSubBg?.cancel();
    await WakelockPlus.disable();
    service.stopSelf();
  });

  // ── Periodic alive-signal: log keepalive and re-acquire wake lock ──
  // Android 12+ deep-doze can suspend timer-based tasks even in foreground
  // services. The wake lock + this periodic tick keeps the CPU alive.
  Timer.periodic(const Duration(seconds: 30), (_) async {
    _foregroundNotifCounter++;
    try {
      await WakelockPlus.enable();
    } catch (_) {}
    debugPrint('[BgService] Alive tick #$_foregroundNotifCounter');
  });

  // Read saved session (group code + user name) from shared_preferences.
  final prefs = await SharedPreferences.getInstance();
  final groupCode = prefs.getString('group_code');
  final userName = prefs.getString('user_name');
  final userIcon = prefs.getString('user_icon');

  if (groupCode == null || userName == null) {
    debugPrint('[BgService] No saved session — GPS loop NOT started.');
    return;
  }

  // Re-authenticate anonymously if needed. Firebase Auth persists the token
  // to disk, so this is idempotent (returns the same UID across isolates).
  try {
    final auth = FirebaseAuth.instance;
    if (auth.currentUser == null) {
      await auth.signInAnonymously();
    }
    final uid = auth.currentUser?.uid;
    if (uid == null || uid.isEmpty) {
      debugPrint('[BgService] Auth failed — no UID. GPS loop NOT started.');
      return;
    }
    debugPrint('[BgService] Authenticated. uid=$uid, group=$groupCode');

    // ── Notifications plugin (for chat messages in background) ──
    final notifPlugin = FlutterLocalNotificationsPlugin();
    const notifSettings = InitializationSettings(
      android: AndroidInitializationSettings('@mipmap/ic_launcher'),
      iOS: DarwinInitializationSettings(),
    );
    await notifPlugin.initialize(notifSettings);
    // Ensure the channel exists for chat notifications
    final androidNotif = notifPlugin.resolvePlatformSpecificImplementation<
        AndroidFlutterLocalNotificationsPlugin>();
    const chatChannel = AndroidNotificationChannel(
      'proximity_channel_v3',
      'Proximity Alerts',
      description: 'Notifications when group members are nearby',
      importance: Importance.max,
    );
    await androidNotif?.createNotificationChannel(chatChannel);

    // ── Chat message listener (shows notification when app is closed) ──
    try {
      final chatRef = FirebaseDatabase.instance.ref('live/$groupCode/_chat');
      _chatSubBg = chatRef.orderByChild('timestamp').onValue.listen((event) {
        final snap = event.snapshot;
        if (!snap.exists) return;
        final data = snap.value as Map<dynamic, dynamic>?;
        if (data == null) return;
        final nowMs = DateTime.now().millisecondsSinceEpoch;
        data.forEach((key, value) {
          if (value is! Map) return;
          final senderId = (value['userId'] as String?) ?? '';
          if (senderId == uid) return;
          final ts = (value['timestamp'] as num?)?.toInt() ?? 0;
          if (ts < nowMs - 60000) return; // only messages within last minute
          final senderName = (value['name'] as String?) ?? 'عضو';
          final msgText = (value['message'] as String?) ?? '';
          debugPrint('[BgService] Chat: $senderName: $msgText');
          notifPlugin.show(
            3000 + senderName.hashCode,
            '📩 $senderName',
            msgText,
            const NotificationDetails(
              android: AndroidNotificationDetails(
                'proximity_channel_v3',
                'Proximity Alerts',
                importance: Importance.max,
                priority: Priority.max,
                showWhen: true,
                playSound: true,
                enableVibration: true,
                visibility: NotificationVisibility.public,
                autoCancel: true,
                category: AndroidNotificationCategory.message,
              ),
              iOS: DarwinNotificationDetails(
                presentAlert: true,
                presentBadge: true,
                presentSound: true,
              ),
            ),
          );
        });
      });
    } catch (e) {
      debugPrint('[BgService] Chat listener setup failed: $e');
    }

    // ── THE GPS LOOP: fires every [kLocationInterval] (3s) ──
    // This is what keeps Firebase updated even when the app is closed.
    int _gpsTick = 0;
    Timer.periodic(kLocationInterval, (timer) async {
      _gpsTick++;
      try {
        // Quick permission/GPS check — skip silently if unavailable so the
        // timer doesn't spam errors when GPS is off.
        final serviceEnabled = await Geolocator.isLocationServiceEnabled();
        if (!serviceEnabled) return;
        final permission = await Geolocator.checkPermission();
        if (permission == LocationPermission.denied ||
            permission == LocationPermission.deniedForever) {
          return;
        }

        final position = await Geolocator.getCurrentPosition(
          locationSettings: const LocationSettings(
            accuracy: LocationAccuracy.high,
          ),
        );

        // Write directly via the shared static function.
        await FirebaseService.writeLocationToFirebase(
          groupCode: groupCode,
          userId: uid,
          name: userName,
          lat: position.latitude,
          lng: position.longitude,
          speed: position.speed,
          icon: userIcon,
        );

        // Push a history point every 10th tick (~30s) for route tracking.
        if (_gpsTick % 10 == 0) {
          await FirebaseService.writeHistoryPoint(
            groupCode: groupCode,
            userId: uid,
            lat: position.latitude,
            lng: position.longitude,
            speed: position.speed,
          );
        }

        final now = DateTime.now();
        final hh = now.hour.toString().padLeft(2, '0');
        final mm = now.minute.toString().padLeft(2, '0');
        final ss = now.second.toString().padLeft(2, '0');
        debugPrint(
          '[BgService] Tick: lat=${position.latitude.toStringAsFixed(5)}, '
          'lng=${position.longitude.toStringAsFixed(5)}, '
          'speed=${position.speed.toStringAsFixed(1)}m/s, '
          'written at $hh:$mm:$ss',
        );
      } catch (e) {
        debugPrint('[BgService] Tick error: $e');
      }
    });
  } catch (e) {
    debugPrint('[BgService] Auth/setup failed: $e');
  }
}

@pragma('vm:entry-point')
bool onIosBackground(ServiceInstance service) {
  return false;
}

class GlovoMateApp extends StatelessWidget {
  const GlovoMateApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'GlovoMate',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorSchemeSeed: const Color(0xFF1565C0),
        useMaterial3: true,
      ),
      home: const SplashScreen(),
    );
  }
}
